# Generated by Django 5.0 on 2025-09-30 09:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feed", models.JSONField()),
                ("date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
