# Generated by Django 5.2.7 on 2025-11-25 08:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("messages", models.JSONField()),
                ("attached_articles", models.JSONField()),
                ("date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
